name: ItemAPIExamplePlugin
version: '1.0.0-SNAPSHOT'
main: me.usainsrht.itemapi.example.ItemAPIExamplePlugin
api-version: '1.21'
authors: [UsainSRHT]
description: Example plugin for testing ItemAPI features
soft-depend: [MiniPlaceholders, itemplaceholder]
commands:
  itemapi:
    description: Get YAML items, reload config, or test item sprites
    usage: /itemapi <yamlitemkey|reload|testsprite>
    permission: itemapi.example
permissions:
  itemapi.example:
    description: Use /itemapi commands
    default: op
