<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>me.usainsrht.itemapi</groupId>
        <artifactId>itemapi</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>yamlitem</artifactId>
    <name>YamlItem</name>
    <description>Shadeable API to parse ItemStacks from YAML using Paper data components</description>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
        </dependency>
    </dependencies>
</project>
